SAML Implementation in Kratos
ovh/kratos pull request #3
Opened 2022-05-03 09:00 UTC by ThibaultHerard

# SAML Implementation 

## Related issue(s)

https://github.com/ory/kratos/issues/1928

2022-05-03 13:42 UTC, Stoakes reviewed
Nice work !

Some questions and a few comments. Mostly on English, Golang & code style.

2022-05-03 13:42 UTC, Stoakes commented on .schema/api.openapi.json
> +        "description": "This endpoint is for the IDP to obtain kratos metadata",
The style for the other descriptions is slightly different.

"This endpoints returns kratos metadata as part of a SAMl login" would be closer to what is done on other endpoints.

2022-05-03 13:42 UTC, Stoakes commented on .schema/api.openapi.json
> +        "description": "This endpoint is to redirect the user to the idp auth flow",
Same as above: style for description text is different from other already existing endpoints.

2022-05-03 13:42 UTC, Stoakes commented on .schema/api.openapi.json
> +        "response": {
I'm missing a few bits on SAML flow, so this might be an irrelevant comment; is it expected there's no 200 response ?

2022-05-03 13:42 UTC, Stoakes commented on .schema/openapi.json
> +        "description": "This endpoint is to redirect the user to the idp auth flow",
All other descriptions are something like "This endpoint + verb at the active form".

2022-05-03 13:42 UTC, Stoakes commented on embedx/config.schema.json
> +          "description": "The URL where the jsonnet source is located for mapping the provider's data to Ory Kratos data.",
misc english wording

```suggestion
          "description": "Location for the jsonnet mapping between provider's data and Ory Kratos data",
```

2022-05-03 13:42 UTC, Stoakes commented on embedx/config.schema.json
> +              "description": "The name of the IDP attribute that will represent the user's firstname on Kratos",
Here and for other attributes

```suggestion
              "description": "Name of the IDP attribute representing user firstname on Kratos",
```

2022-05-03 13:42 UTC, Stoakes commented on persistence/sql/migrations/legacy/20220415152108_credentials_types_saml.up.fizz
> +sql("INSERT INTO identity_credential_types (id, name) SELECT 'ff5a1823-8b47-4255-860f-4b70ed122740', 'saml' WHERE NOT EXISTS ( SELECT * FROM identity_credential_types WHERE name = 'saml')")
Sorry for missing context: what is behind `ff5a1823-8b47-4255-860f-4b70ed122740` ?

2022-05-03 13:42 UTC, Stoakes commented on postgres.yaml
> +version: '3.7'
Is this file committed on purpose ?

2022-05-03 13:42 UTC, Stoakes commented on postgres.yaml
> +      image: postgres:9.6
This postgres version is antic btw

2022-05-03 13:42 UTC, Stoakes commented on internal/httpclient/model_self_service_saml_url.go
> +	if true {
This condition will always be true, so it can be removed.

Same for the other ones below.

2022-05-03 13:42 UTC, Stoakes commented on internal/httpclient/model_self_service_saml_url.go
> +		return ret
Could be compacted into a single `return ""` statement.

2022-05-03 13:42 UTC, Stoakes commented on internal/httpclient/model_self_service_saml_url.go
> +		return ret
Same comment than L49

2022-05-03 13:42 UTC, Stoakes commented on selfservice/flow/saml/handler.go
> +	if c.SAMLProviders[len(c.SAMLProviders)-1].IDPInformation["idp_metadata_url"] != "" {
I feel like this access lacks safety railings:

 * if len(c.SAMLProviders) == 0 this method will panic. Example at https://go.dev/play/p/AAD95wCtX_P
 * Is IDPInformation always initialized ?
 * Is idp_metadata_url always set ? Aren't there cases when it is empty but still valid ?

```suggestion
	if len(c.SAMLProviders) > 0 {
	     if val, ok := c.SAMLProviders[len(c.SAMLProviders)-1].IDPInformation["idp_metadata_url"]; ok && len(val) > 0 {
```

2022-05-03 13:42 UTC, Stoakes commented on selfservice/strategy/saml/provider_config.go
> +	// Represent the path of the certificate of your application
Standard Golang comment format is // <variable name> <description>

```suggestion
	// PublicCertPath path of your application certificate
```

Same for other variables below

2022-05-03 13:42 UTC, Stoakes commented on selfservice/strategy/saml/provider_saml.go
> +		Subject:       SAMLAttribute.Get(c.SAMLProviders[len(c.SAMLProviders)-1].AttributesMap["id"]),
Are we sure at this point of the code that `len(c.SAMLProviders)` is > 0 ?

2022-05-03 13:42 UTC, Stoakes commented on selfservice/strategy/saml/provider_saml.go
> +		EmailVerified: true,
is `EmailVerified` truly always true at this point of the code ?

2022-05-03 13:42 UTC, Stoakes commented on selfservice/strategy/saml/strategy/strategy.go
> +	// AddSamlProviders(c, conf.Providers, message)
Commented code can be removed

2022-05-03 13:42 UTC, Stoakes commented on selfservice/strategy/saml/strategy/strategy.go
> +func (s *Strategy) CountActiveCredentials(cc map[identity.CredentialsType]identity.Credentials) (count int, err error) {
Personal preference: returning explicitly values instead of using named return argument. I do so, because I find it less error prone.

2022-05-03 13:42 UTC, Stoakes commented on selfservice/strategy/saml/strategy/strategy.go
> +func (s *Strategy) CountActiveFirstFactorCredentials(cc map[identity.CredentialsType]identity.Credentials) (count int, err error) {
This function requires a bit of reading to fully understand what it does; it might be interesting to add a comment describing what it does.

2022-05-03 13:42 UTC, Stoakes commented on selfservice/strategy/saml/strategy/strategy_auth.go
> +// Handle SAML Assertion and process to either login or register
golang standard comment format starts with variable of function name.

Kratos uses a different one: https://github.com/ovh/kratos/blob/af1df63c62a8aec52f6adf9f23bb5dbd38c491ed/selfservice/flow/recovery/handler.go#L203

To be adapted based on your knowledge of ory coding style.

2022-05-03 13:42 UTC, Stoakes commented on selfservice/strategy/saml/strategy/strategy_auth.go
> +				} else {
Unused else: No need to add a `else` when last statement of an `if` is a return.

Here and below

2022-05-03 14:07 UTC, psauvage0 requested changes
Great work ! :D 

The main problem I see is with the attribute mapping that only works with a fixed list of attributes names. 

Otherwise it's about small code quality improvements. There are some pointed out by the linter that I didn't bother to comment as they are already shown in the PR builds.

I honestly think that we could already take reviews from the Ory team & community, as there are maybe some things about how they want the code to be organized.

2022-05-03 14:07 UTC, psauvage0 commented on embedx/config.schema.json
> +        "public_cert_path": {
certificate_path ? Or public_key_certificate_path ?

2022-05-03 14:07 UTC, psauvage0 commented on embedx/config.schema.json
> +        "attributes_map": {
The attributes mapping is given in the config ? What if I have an attribute that is not provided here ? For example `group` ?

2022-05-03 14:07 UTC, psauvage0 commented on internal/httpclient/api/openapi.yaml
> +  /self-service/methods/saml/auth:
Not related to the doc but to the route of this call (I don't know where the route is defined). 

In the [Ory Documentation for the API](https://www.ory.sh/docs/kratos/reference/api#operation/initializeSelfServiceLoginFlowWithoutBrowser), we can see that when there are different calls to make for browser vs API, they usually end the route with `/browser` or `/api`.  Maybe the same can be applied here ?

2022-05-03 14:07 UTC, psauvage0 commented on selfservice/flow/saml/handler.go
> +	keyPair, err := tls.LoadX509KeyPair(strings.Replace(c.SAMLProviders[len(c.SAMLProviders)-1].PublicCertPath, "file://", "", 1), strings.Replace(c.SAMLProviders[len(c.SAMLProviders)-1].PrivateKeyPath,
No Out Of Bound possible here ?

2022-05-03 14:07 UTC, psauvage0 commented on selfservice/flow/saml/handler.go
> +	if c.SAMLProviders[len(c.SAMLProviders)-1].IDPInformation["idp_metadata_url"] != "" {
OOB ? 
Also, you can check if a map entry is set with something like `if value, ok := mymap["key"]; ok { ...`
```suggestion
	if metadataURL, ok := c.SAMLProviders[len(c.SAMLProviders)-1].IDPInformation["idp_metadata_url"]; ok {
```

2022-05-03 14:07 UTC, psauvage0 commented on selfservice/flow/saml/handler.go
> +	if publicUrlString[len(publicUrlString)-1] != '/' {
You could probably simplify this with something like `strings.TrimSuffix(strings.TrimSuffix(publicURLString, "/"), "/") + "/"`.
See https://pkg.go.dev/strings#TrimSuffix for more info

2022-05-03 14:07 UTC, psauvage0 commented on selfservice/flow/saml/handler.go
> +	}
```suggestion
  u, err := url.Parse(strings.TrimSuffix(strings.TrimSuffix(publicURLString, "/"), "/") + "/"+ RouteSamlAcsWithSlash)
  if err != nil {
	  return err
  }
  samlMiddleWare.ServiceProvider.AcsURL = *u

```

2022-05-03 14:07 UTC, psauvage0 commented on selfservice/flow/saml/handler.go
> +		return nil, errors.Errorf("The MiddleWare for SAML is null (Probably due to a backward step)")
There is no null in go :p

2022-05-03 14:07 UTC, psauvage0 commented on selfservice/flow/saml/handler.go
> +		return nil, errors.Errorf("The MiddleWare for SAML is null (Probably due to a backward step)")
Joke aside, I don't understand the backward step part, the error message is a bit unclear

2022-05-03 14:07 UTC, psauvage0 commented on selfservice/strategy/saml/provider.go
> +type Claims struct {
I couldn't find anything like this type Claims in the other strategies... Is it used to handle attribute mapping ? If so see previous comment about attribute mapping config

2022-05-03 14:07 UTC, psauvage0 commented on selfservice/strategy/saml/provider.go
> +type Claims struct {
I couldn't find Claims like those in other strategies. Is it linked to attribute mapping ?

2022-05-03 14:07 UTC, psauvage0 commented on selfservice/strategy/saml/provider_saml.go
> +	}
Attribute mapping needs to be able to take into account user defined attributes. What if I need the attribute `group` from the IDP to map to a `group` trait I configured in a Kratos Identity schema ?

2022-05-03 14:07 UTC, psauvage0 commented on selfservice/strategy/saml/strategy/strategy.go
> +	r.ParseForm()
Error is not checked

2022-05-03 14:07 UTC, psauvage0 commented on selfservice/strategy/saml/strategy/strategy.go
> +	provider, err := c.Provider(c.SAMLProviders[len(c.SAMLProviders)-1].ID, c.SAMLProviders[len(c.SAMLProviders)-1].Label)
No OOB possible ?

2022-05-03 14:07 UTC, psauvage0 commented on selfservice/strategy/saml/strategy/strategy.go
> +			traitNodes, err := container.NodesFromJSONSchema(r.Context(), node.OpenIDConnectGroup, ds.String(), "", nil)
Use SAMLGroup node ?

2022-05-03 14:07 UTC, psauvage0 commented on selfservice/strategy/saml/strategy/strategy.go
> +			rf.UI.UpdateNodeValuesFromJSON(traits, "traits", node.OpenIDConnectGroup)
Here too

2022-05-03 14:07 UTC, psauvage0 commented on selfservice/strategy/saml/strategy/strategy.go
> +				if parts[0] == conf.Providers[0].Provider && parts[1] == conf.Providers[0].Subject && len(conf.Providers[0].Subject) > 1 && len(conf.Providers[0].Provider) > 1 {
Possible OOB with `conf.Providers[0]` ?

2022-05-03 14:07 UTC, psauvage0 commented on selfservice/strategy/saml/strategy/strategy.go
> +			var conf identity.CredentialsOIDC
`identity.CredentialsOIDC` in SAML strategy ?

2022-05-03 14:07 UTC, psauvage0 commented on selfservice/strategy/saml/strategy/strategy.go
> +func (s *Strategy) CountActiveMultiFactorCredentials(cc map[identity.CredentialsType]identity.Credentials) (count int, err error) {
Not implemented ?

2022-05-03 14:07 UTC, psauvage0 commented on selfservice/strategy/saml/strategy/strategy_auth.go
> +		// The user already exist in database so we log him
This makes me think : what happens when the IDP deletes a user ? I guess the user remains in the SP forever... What are the consequences of that ? It should not be a problem at all, but we could investigate this case a bit

2022-05-03 14:07 UTC, psauvage0 commented on selfservice/strategy/saml/strategy/strategy_login.go
> +// Method not used but necessary to implement the interface
I find this weird but if you say so 🤨

2022-05-03 14:07 UTC, psauvage0 commented on selfservice/strategy/saml/strategy/test/strategy_test.go
> +func TestGetAndDecryptAssertion(t *testing.T) {
Unrelated to the code : it would be interesting to discuss test strategy with the Ory community. It seems there is not a lot of info on what is considered a good level of testing on `CONTRIBUING.md` file (should we cover all branches of a functions ? Should we test for edge cases ? Or simply testing the main intent of the function is OK ?)

2022-05-03 14:07 UTC, psauvage0 commented on spec/api.json
> +    "/self-service/methods/saml/auth": {
Same thing as before about the route : `/browser` vs `/api` routes

2022-05-03 14:59 UTC, sebferrer commented on internal/httpclient/api/openapi.yaml
> +  /self-service/methods/saml/auth:
We did it on purpose based on a misunderstanding, indeed we should change it back

2022-05-03 15:03 UTC, sebferrer commented on selfservice/strategy/saml/strategy/strategy.go
> +func (s *Strategy) CountActiveMultiFactorCredentials(cc map[identity.CredentialsType]identity.Credentials) (count int, err error) {
Not yet. This implementation isn't required since a long time, so we had to do it like this on our last rebase.

2022-05-03 15:23 UTC, sebferrer commented on selfservice/strategy/saml/strategy/strategy_login.go
> +// Method not used but necessary to implement the interface
Here's the kind of error we get otherwise:
```
# github.com/ory/kratos/selfservice/strategy/saml/strategy
selfservice/strategy/saml/strategy/strategy_login.go:25:24: cannot use new(Strategy) (value of type *Strategy) as type login.Strategy in variable declaration:
        *Strategy does not implement login.Strategy (missing Login method)
```

2022-05-04 13:47 UTC, psauvage0 commented on selfservice/strategy/saml/strategy/strategy_login.go
> +// Method not used but necessary to implement the interface
What I found weird was that the method is called "Login", so I would expect that it is a pretty important method to implement in an IAM.

2022-05-04 15:33 UTC, ThibaultHerard commented on embedx/config.schema.json
> +        "attributes_map": {
For the moment, this part is not configurable, that is to say that the identity cannot have more fields than what is present here.

2022-05-04 15:51 UTC, ThibaultHerard commented on selfservice/strategy/saml/provider_saml.go
> +	}
For the moment, the user can't add attributes as he wants but maybe I should add a group attribute

2022-05-04 16:06 UTC, ThibaultHerard commented on selfservice/strategy/saml/strategy/strategy_auth.go
> +		// The user already exist in database so we log him
This is indeed what will happen but it is complicated for the SP to know that the IDP has deleted a user

2023-01-05 13:22 UTC, closed without merging